accounts/urls.py
"""Account urls

Now, you want to create a login page for the user. Start by creating a templates/authentication/
login.html in the user_auth/ folder. Now, set up your user_login view in views.py to take the user
to the login page:"""

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views
app_name = 'accounts'
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('add_profile', views.add_profile, name='add-profile'),
]

band/urls.py
"""Band urls"""

from django.urls import path
from . import views


app_name = 'band'
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('songs', views.songs, name='songs'),
]

mysite/urls.py
"""Urls for mysite project
Add a URL that will point to your app.
Append the urls so that they will point to your applications in urls.py"""

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('band.urls')),
    path('accounts/', include('accounts.urls')),

]

accounts/models.py
from django.db import models
"""Accounts Model

Refers to the reference source for the database fields and associated behaviour for the data you consume
in your application. This app will need to store the content of each user's information.  Each class in 
models.py is a database table. Each attribute/variable of the model represents a database field. 
You specify a data type and maybe some further attributes (e.g. max_length) for each attribute."""


from django.contrib.auth.models import User


class UserInterest(models.Model):
    name = models.CharField(max_length=65, unique=True)
    normalised_name = models.CharField(max_length=65, unique=True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=65, unique=True)
    normalised_name = models.CharField(max_length=65, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    is_full_name_displayed = models.BooleanField(default=True)
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200,blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)
    interests = models.ManyToManyField(UserInterest, blank=True)

band/models.py
from django.db import models

# Create your models here.

accounts/forms.py
"""Django ModelForm is a class that is used to directly convert a model into a Django form. Because
you are building a database-driven app, the forms are map closely to Django models"""

from django import forms
from django.forms import ModelForm
from .models import UserProfile


class ProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user', 'is_full_name_displayed', 'bio', 'website', 'interests')

        widgets = {
            'user': forms.TextInput(attrs={'class': 'form-control'}),
            'is_full_name_displayed': forms.TextInput(attrs={'class': 'form-control'}),
            'bio': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.TextInput(attrs={'class': 'form-control'}),
            'interests': forms.TextInput(attrs={'class': 'form-control'}),
        }

accounts/views.py
"""Accounts View

Contains the logic that governs the user's request and determines the appropriate response.
View doesn’t necessarily mean ‘display’.

Accounts View relates your Model and Template together through URLs.
The View component helps to determine which information data in your Model should be communicated via
your Template"""

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import UserProfile
from .forms import ProfileForm


def add_profile(request: HttpRequest) -> HttpResponse:
    submitted = False
    if request.method == "POST":
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/accounts/add_profile?submitted=True')
    else:
        form = ProfileForm
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'accounts/add_profile.html', {'form': form, 'submitted': submitted})


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

band/views.py
""" My band views

View: contains the logic that governs the user’s request and determines the appropriate response.
View doesn’t necessarily mean ‘display’.

Band view relates your Model and Template together through URLs.
The View component helps to determine which information data in your Model should be communicated via
your Template"""

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse


def index (request: HttpRequest) -> HttpResponse:
    return render(request, 'band/index.html')

def about (request: HttpRequest) -> HttpResponse:
    return render(request,'band/about.html')

def songs (request: HttpRequest) -> HttpResponse:
    return render(request,'band/songs.html')

accounts/templates/accounts/Profile.html
{% extends 'band/base.html' %}
{% load static %}

{% block title %}profile{% endblock %}
{% block content %}


<h1>
  {{ user.get_full_name }} (@{{user.username}})
</h1>
{% with profile=user.profile %}
  {% if profile %}
    <h2>
      {{ profile.persona|default:""}}
    </h2>
    <div>
      {{profile.boi|default:""}}
    </div>
    <div>
      {% with website=profile.website|default:"" %}
        <a href="{{website}}">{{website}}</a>
      {% endwith %}
    </div>
    <br/>
    <div>
      Intersets:
      {% for interest in profile.interests.all %}
        <span>
          {{interest.name}}{% if not forloop.last %},{% endif %}
        </span>
      {% endfor %}
    </div>
  {% endif %}
{% endwith %}
{% endblock %}

accounts/templates/accounts/add_profile.html
{% extends 'band/base.html' %}
{% load static %}

{% block title %}profile{% endblock %}
{% block content %}

<center>
<h1>
Add Profile
</h1>
<br/><br/>
{% if submitted %}
    Your profile was submitted successfully!!!

{% else %}
    <form action="" method = POST>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="btn btn-secondary">
    </form>

{% endif %}
</center>
<div>


            <p>


            </p>

</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'band/base.html' %}
{% load static %}

{% block title %}about{% endblock %}
{% block content %}


<h1>Login</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

{% endblock %}

band/templates/band/about.html
{% extends 'band/base.html' %}
{% load static %}


{% block content %}


<h1>
About
</h1>
<div>


            <p>
                The Potheads are an English girl group formed in 1998, consisting of Hermione Granger a.k.a. Brainy ;
                Ginny Weasley aka Sporty; and Luna Lovegood aka Whimsy. With their "harry potter power" mantra, they
                redefined the girl-group concept by targeting a young female fanbase. They led the teen pop resurgence
                of the 1990s and 2000s, were a major part of the Cool Britannia era, and became pop culture icons of
                the decades.
            </p>

</div>
{% endblock %}

band/templates/band/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PotterHeads</title>

     <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />

        <link href="{% static 'css/main.css' %}" rel="stylesheet" />

</head>





<body>
{% include 'band/navbar.html' %}
  <main id="main">
    {% block content %}
    {% endblock %}
  </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'theme/js/styles.js' %}"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

band/templates/band/index.html
{% extends 'band/base.html' %}
{% load static %}

{% block title %}home{% endblock %}
{% block content %}

  <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <img class="masthead-avatar mb-5" src="{% static 'theme/assets/img/ladies.jpg' %}" alt="..." />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">We Will Rock You!!!</h1>

            </div>
        </header>

<h1>

</h1>

{% endblock %}

band/templates/band/navbar.html
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="{{ index_url }}">PØTTƎɌ HƎΔDS</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% url 'band:index' as index_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Home</a></li>
                       {% url 'band:about' as about_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                        {% url 'band:songs' as songs_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == song_url %}active{% endif %}" href="{{ songs_url }}">Songs</a></li>

                       {% url 'accounts:add-profile' as add_profile_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == add_profile_url %}active{% endif %}" href="{{ add_profile_url }}">Add Profile</a></li>

                            {% if user.is_authenticated %}
                            {% url 'accounts:profile' as profile_url %}
                            <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == profile_url %}active{% endif %}" href="{{ profile_url }}">Profile</a></li>


                        <span><a href="{%url 'accounts:logout' %}">Logout</a></span>
                            {% else %}
                            <span><a href="{%url 'accounts:login' %}">Login</a></span>
                            {% endif %}
                         </span>

                    </ul>
                </div>
            </div>
        </nav>

band/templates/band/songs.html
{% extends 'band/base.html' %}
{% load static %}

{% block title %}songs{% endblock %}
{% block content %}


<h1>
Songs
</h1>
<div>


            <p>
                <div> Do the Hippogriff </div>
                <div>Magic Works</div>
                <div>This Is the Night</div>
                <div>O' scilent Halloween night</div>
                <div>Dumbledore Rocks!</div>
                <div>Creepy Crawly</div>

            </p>

</div>
{% endblock %}